### ISSUE TITLE
Unable to register (dev & prod).  "CONNECTION_REFUSED

### ISSUE THREAD

**Issue by teamhail** [iurii-kyrylenko/hobbies#9]
Thanks the help with the ReCAPTCHA config.  I wanted to confirm that ReCAPTCHA because I  can't register any users for dev or prod.  I also haven't been able to get the unit (or E2E) test running.  I have not made any changes to any of the src -- I made a fresh install,  ran npm install for both front-end and server, and run build.  

node v8.8.1, npm 5.4.2, Vue v2.5.8

For DEV I get `http://localhost:3000/api/users/register net::ERR_CONNECTION_REFUSED`

For PROD with a correct .env file running heroku local gives the following error:
`TypeError: The "digest" argument is required and must not be undefined at pbkdf2 (crypto.js:636:11) at Object.exports.pbkdf2Sync (crypto.js:629:10)`

For Unit Tests, I get 
`ERROR in ./test/unit/index.js Module build failed: Error: Couldn't find preset "latest" relative to directory ....`

I made several attempts to debug changing the babelrc file (like removing "latest" and adding "env").  I also am getting the correct ReCAPTCHA event returned.  Thanks again for the help.

**Comment by iurii-kyrylenko** [comment]
> TypeError: The "digest" argument is required and must not be undefined at pbkdf2

Fixed this. Pull the latest changes for the server.

**Comment by teamhail** [comment]
Thanks very much.  Prod is working fine now.

However, I still can't get Dev working.  Nor any test.  I keep getting `http://localhost:3000/api/users/register net::ERR_CONNECTION_REFUSED`

Am I supposed to make a .env for the front-end?  I'm confused where I'm supposed to set CORS to "yes" for the vuejs client.

**Comment by iurii-kyrylenko** [comment]
.env file resides on back-end. This is how it looks to work with front-end, hosted on dev-server:
```
    CONNECTION_STRING = <connection string to mongodb>
    JWT_SECRET = <JWT secret key>
    CAPTCHA_SECRET = <The shared key between my site and ReCAPTCHA>
    CAPTCHA_API = https://www.google.com/recaptcha/api/siteverify
    TMDB_API = https://api.themoviedb.org/3/
    TMDB_API_KEY = <TMDB api key>
    TMDB_IMAGE_STORE = https://image.tmdb.org/t/p/
    ALLOW_CORS = yes
    PORT = 3000
```
In dev mode the API is called from JS, hosted on different server. So back-end should enable CORS. In prod we have only one server for hosting both API and client JS and don’t need cross origin resource sharing.

**Comment by teamhail** [comment]
Got it working.  I had assumed there was no need to run the backend at the same time as the front-end when Webpack was running for Dev.  Thanks again for the help.
